"""baseline: all current tables

Revision ID: 05831774f213
Revises: 
Create Date: 2026-09-26 10:22:21.501191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('icon', sa.String(length=16), nullable=False),
    sa.Column('category', sa.Enum('activity', 'streak', 'reactions', 'pet', 'social', 'secret', name='achievementcategory', native_enum=False), nullable=False),
    sa.Column('condition_type', sa.Enum('messages_total', 'messages_day', 'streak_days', 'reactions_given', 'reactions_received', 'pet_feeds', 'pet_level', 'pet_walks', 'invites', 'top1_day', 'level', 'coins_earned', 'games_won', name='conditiontype', native_enum=False), nullable=False),
    sa.Column('condition_value', sa.Integer(), nullable=False),
    sa.Column('reward_xp', sa.Integer(), nullable=False),
    sa.Column('reward_coins', sa.Integer(), nullable=False),
    sa.Column('is_hidden', sa.Boolean(), nullable=False),
    sa.Column('rarity', sa.Enum('common', 'rare', 'epic', 'legendary', name='achievementrarity', native_enum=False), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_table('channel_subscribers',
    sa.Column('user_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('chat_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('first_name', sa.String(length=128), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('welcomed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('welcome_sent_chat_id', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('user_id', 'chat_id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    with op.batch_alter_table('channel_subscribers', schema=None) as batch_op:
        batch_op.create_index('ix_channel_subscribers_first_seen', ['first_seen'], unique=False)

    op.create_table('chat_settings',
    sa.Column('chat_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('welcome_enabled', sa.Boolean(), nullable=False),
    sa.Column('welcome_text', sa.Text(), nullable=True),
    sa.Column('cooldown_sec', sa.Integer(), nullable=False),
    sa.Column('min_length', sa.Integer(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('chat_id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('icon', sa.String(length=16), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('effect', sa.JSON(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_table('leaderboards_snapshot',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('period', sa.String(length=16), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_table('users',
    sa.Column('tg_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('first_name', sa.String(length=128), nullable=False),
    sa.Column('last_name', sa.String(length=128), nullable=True),
    sa.Column('lang', sa.String(length=8), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('xp', sa.Integer(), nullable=False),
    sa.Column('coins', sa.Integer(), nullable=False),
    sa.Column('streak_days', sa.Integer(), nullable=False),
    sa.Column('best_streak', sa.Integer(), nullable=False),
    sa.Column('last_active_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('onboarded', sa.Boolean(), nullable=False),
    sa.Column('pet_name', sa.String(length=64), nullable=True),
    sa.Column('is_banned', sa.Boolean(), nullable=False),
    sa.Column('referrer_id', sa.BigInteger(), nullable=True),
    sa.Column('settings_extra', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('messages_count', sa.Integer(), nullable=False),
    sa.Column('reactions_given', sa.Integer(), nullable=False),
    sa.Column('reactions_received', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('tg_id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_table('chat_messages_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('length', sa.Integer(), nullable=False),
    sa.Column('has_media', sa.Boolean(), nullable=False),
    sa.Column('media_type', sa.String(length=32), nullable=True),
    sa.Column('is_reply', sa.Boolean(), nullable=False),
    sa.Column('mentions_count', sa.Integer(), nullable=False),
    sa.Column('is_counted', sa.Boolean(), nullable=False),
    sa.Column('skip_reason', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.tg_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chat_id', 'message_id', name='uq_cml_chat_msg'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    with op.batch_alter_table('chat_messages_log', schema=None) as batch_op:
        batch_op.create_index('ix_cml_chat_created', ['chat_id', 'created_at'], unique=False)
        batch_op.create_index('ix_cml_user_created', ['user_id', 'created_at'], unique=False)

    op.create_table('notification_settings',
    sa.Column('user_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('pet_reminders', sa.Boolean(), nullable=False),
    sa.Column('streak_reminders', sa.Boolean(), nullable=False),
    sa.Column('achievement_notifications', sa.Boolean(), nullable=False),
    sa.Column('daily_report', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.tg_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_table('notifications_queue',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('send_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent', sa.Boolean(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.tg_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_table('pets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('species', sa.Enum('cat', 'dog', 'fox', 'owl', 'dragon', name='petspecies', native_enum=False), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('xp', sa.Integer(), nullable=False),
    sa.Column('stage', sa.Enum('egg', 'baby', 'teen', 'adult', 'legendary', name='petstage', native_enum=False), nullable=False),
    sa.Column('hunger', sa.Float(), nullable=False),
    sa.Column('happiness', sa.Float(), nullable=False),
    sa.Column('energy', sa.Float(), nullable=False),
    sa.Column('hygiene', sa.Float(), nullable=False),
    sa.Column('health', sa.Float(), nullable=False),
    sa.Column('strength', sa.Integer(), nullable=False),
    sa.Column('agility', sa.Integer(), nullable=False),
    sa.Column('intellect', sa.Integer(), nullable=False),
    sa.Column('is_sleeping', sa.Boolean(), nullable=False),
    sa.Column('sleep_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('walk_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sick_since', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_update', sa.DateTime(timezone=True), nullable=False),
    sa.Column('born_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('settings_extra', sa.JSON(), nullable=False),
    sa.Column('generation', sa.Integer(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archive_reason', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.tg_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_table('reactions_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('from_user', sa.BigInteger(), nullable=False),
    sa.Column('to_user', sa.BigInteger(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('emoji', sa.String(length=16), nullable=False),
    sa.Column('is_counted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['from_user'], ['users.tg_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_user'], ['users.tg_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_user', 'message_id', 'emoji', name='uq_reaction_once'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    with op.batch_alter_table('reactions_log', schema=None) as batch_op:
        batch_op.create_index('ix_rl_to_created', ['to_user', 'created_at'], unique=False)

    op.create_table('user_achievements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('achievement_id', sa.Integer(), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('unlocked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['achievement_id'], ['achievements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.tg_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'achievement_id', name='uq_user_ach'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_table('user_stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('key', sa.String(length=32), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.tg_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'key', name='uq_user_stat'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_table('pet_actions_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pet_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    with op.batch_alter_table('pet_actions_log', schema=None) as batch_op:
        batch_op.create_index('ix_pal_pet_created', ['pet_id', 'created_at'], unique=False)

    op.create_table('pet_duels',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pet_id', sa.Integer(), nullable=False),
    sa.Column('week_key', sa.String(length=12), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.Column('losses', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('fights', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pet_id', 'week_key', name='uq_pet_duel_week'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    with op.batch_alter_table('pet_duels', schema=None) as batch_op:
        batch_op.create_index('ix_pd_week_score', ['week_key', 'score'], unique=False)

    op.create_table('pet_friends',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pet_id', sa.Integer(), nullable=False),
    sa.Column('friend_pet_id', sa.Integer(), nullable=False),
    sa.Column('since', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['friend_pet_id'], ['pets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pet_id', 'friend_pet_id', name='uq_pet_friend'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_table('pet_inventory',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pet_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pet_id', 'item_id', name='uq_pet_item'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pet_inventory')
    op.drop_table('pet_friends')
    with op.batch_alter_table('pet_duels', schema=None) as batch_op:
        batch_op.drop_index('ix_pd_week_score')

    op.drop_table('pet_duels')
    with op.batch_alter_table('pet_actions_log', schema=None) as batch_op:
        batch_op.drop_index('ix_pal_pet_created')

    op.drop_table('pet_actions_log')
    op.drop_table('user_stats')
    op.drop_table('user_achievements')
    with op.batch_alter_table('reactions_log', schema=None) as batch_op:
        batch_op.drop_index('ix_rl_to_created')

    op.drop_table('reactions_log')
    op.drop_table('pets')
    op.drop_table('notifications_queue')
    op.drop_table('notification_settings')
    with op.batch_alter_table('chat_messages_log', schema=None) as batch_op:
        batch_op.drop_index('ix_cml_user_created')
        batch_op.drop_index('ix_cml_chat_created')

    op.drop_table('chat_messages_log')
    op.drop_table('users')
    op.drop_table('leaderboards_snapshot')
    op.drop_table('items')
    op.drop_table('chat_settings')
    with op.batch_alter_table('channel_subscribers', schema=None) as batch_op:
        batch_op.drop_index('ix_channel_subscribers_first_seen')

    op.drop_table('channel_subscribers')
    op.drop_table('achievements')
    # ### end Alembic commands ###
